// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface ISP1Verifier {
    function verify(
        bytes32 programVKey,
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external view;
}

interface IDisputeRegistry {
    function resolveFromVerifier(uint256 playId, bool isOffside) external;
}

contract ZKVerifier {
    address public owner;
    address public disputeRegistry;
    address public sp1Verifier;
    bytes32 public programVKey;
    
    bool public isMockEnabled;

    event ProofVerified(uint256 indexed playId, bool isOffside, bytes32 programVKey);
    event MockVerificationToggled(bool enabled);
    event ConfigUpdated(address sp1Verifier, bytes32 programVKey);

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner");
        _;
    }

    constructor(address _sp1Verifier, bytes32 _programVKey) {
        owner = msg.sender;
        sp1Verifier = _sp1Verifier;
        programVKey = _programVKey;
        isMockEnabled = true; // Default true for flexible local testing and hackathon demonstration
    }

    function setDisputeRegistry(address _disputeRegistry) external onlyOwner {
        require(_disputeRegistry != address(0), "Invalid registry address");
        disputeRegistry = _disputeRegistry;
    }

    function updateConfig(address _sp1Verifier, bytes32 _programVKey) external onlyOwner {
        sp1Verifier = _sp1Verifier;
        programVKey = _programVKey;
        emit ConfigUpdated(_sp1Verifier, _programVKey);
    }

    function toggleMockVerification(bool _enabled) external onlyOwner {
        isMockEnabled = _enabled;
        emit MockVerificationToggled(_enabled);
    }

    /**
     * @notice Verifies the SP1 ZK proof for a given play and updates the DisputeRegistry.
     * @param playId The ID of the play being disputed.
     * @param isOffside The deterministic AI output (true/false) being verified.
     * @param publicValues The public values generated by the SP1 guest program. Should encode (playId, isOffside).
     * @param proofBytes The actual SP1 cryptographic proof.
     */
    function verifyPlayProof(
        uint256 playId,
        bool isOffside,
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external {
        require(disputeRegistry != address(0), "Dispute registry not set");

        if (isMockEnabled) {
            // Under mock mode, we simulate verification for presentation and initial deployment purposes
            // This allows the dapp to be fully functional on X Layer Testnet immediately
            emit ProofVerified(playId, isOffside, programVKey);
        } else {
            // Decode and validate that public values match the transaction inputs
            (uint256 decodedPlayId, bool decodedIsOffside) = abi.decode(publicValues, (uint256, bool));
            require(decodedPlayId == playId, "Play ID mismatch");
            require(decodedIsOffside == isOffside, "Offside verdict mismatch");

            // Perform actual verification via Succinct's SP1 Verifier contract
            ISP1Verifier(sp1Verifier).verify(programVKey, publicValues, proofBytes);
            emit ProofVerified(playId, isOffside, programVKey);
        }

        // Call the dispute registry to resolve the controversy using the verified ZK-AI verdict
        IDisputeRegistry(disputeRegistry).resolveFromVerifier(playId, isOffside);
    }
}
