// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface ISP1Verifier {
    function verifyProof(
        bytes32 programVKey,
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external view;
}

interface IDisputeRegistry {
    function resolveFromVerifier(uint256 playId, bool isOffside) external;
}

contract ZKVerifier {
    address public owner;
    address public disputeRegistry;
    address public sp1Verifier;
    bytes32 public programVKey;

    mapping(uint256 => bytes32) public playDataHashes;

    event ProofVerified(uint256 indexed playId, bool isOffside, bytes32 programVKey);
    event ConfigUpdated(address sp1Verifier, bytes32 programVKey);
    event PlayDataCommitted(uint256 indexed playId, bytes32 dataHash);

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner");
        _;
    }

    constructor(address _sp1Verifier, bytes32 _programVKey) {
        require(_sp1Verifier != address(0), "Invalid SP1 verifier");
        require(_programVKey != bytes32(0), "Invalid program vkey");
        owner = msg.sender;
        sp1Verifier = _sp1Verifier;
        programVKey = _programVKey;
    }

    function setDisputeRegistry(address _disputeRegistry) external onlyOwner {
        require(_disputeRegistry != address(0), "Invalid registry address");
        disputeRegistry = _disputeRegistry;
    }

    function updateConfig(address _sp1Verifier, bytes32 _programVKey) external onlyOwner {
        require(_sp1Verifier != address(0), "Invalid SP1 verifier");
        require(_programVKey != bytes32(0), "Invalid program vkey");
        sp1Verifier = _sp1Verifier;
        programVKey = _programVKey;
        emit ConfigUpdated(_sp1Verifier, _programVKey);
    }

    function commitPlayData(uint256 playId, bytes32 dataHash) external onlyOwner {
        require(dataHash != bytes32(0), "Invalid data hash");
        require(playDataHashes[playId] == bytes32(0), "Play data already committed");
        playDataHashes[playId] = dataHash;
        emit PlayDataCommitted(playId, dataHash);
    }

    /**
     * @notice Verifies the SP1 ZK proof for a given play and updates the DisputeRegistry.
     * @param playId The ID of the play being disputed.
     * @param isOffside The verified referee-review outcome.
     * @param publicValues The public values generated by the SP1 guest program. Should encode (playId, isOffside).
     * @param proofBytes The actual SP1 cryptographic proof.
     */
    function verifyPlayProof(
        uint256 playId,
        bool isOffside,
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external {
        require(disputeRegistry != address(0), "Dispute registry not set");
        require(proofBytes.length > 0, "Proof bytes required");

        // Decode and validate that public values match the transaction inputs and committed data.
        (uint256 decodedPlayId, bool decodedIsOffside, bytes32 decodedDataHash) =
            abi.decode(publicValues, (uint256, bool, bytes32));
        require(decodedPlayId == playId, "Play ID mismatch");
        require(decodedIsOffside == isOffside, "Offside verdict mismatch");
        require(decodedDataHash != bytes32(0), "Invalid public data hash");
        require(playDataHashes[playId] == decodedDataHash, "Uncommitted play data");

        // Verify the proof through Succinct's SP1 verifier contract.
        ISP1Verifier(sp1Verifier).verifyProof(programVKey, publicValues, proofBytes);
        emit ProofVerified(playId, isOffside, programVKey);

        // Resolve the dispute using the verified SP1 outcome.
        IDisputeRegistry(disputeRegistry).resolveFromVerifier(playId, isOffside);
    }
}
